version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/public'
    schedule:
      interval: 'daily'
    allow-auto-merge: true

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    allow-auto-merge: true
