# KerogsPHP Framework Configuration
# https://github.com/KSInfinite/KerogsPHP-Framework
# Thanks for using it.

# SEO Configuration
seo:
  title: "SoftScan4"
  title_short: "SoftScan4"
  description: "v4 de SoftScan, SoftScan est un site de partage de fichier média qui fonctionne avec des outils comme FFMPEG et YT-DLP"
  keywords: "Galerie, Image, Scan, Video, Live, GIF, Dossier, Clef usb, disque dur, image"
  author: "Kerogs"
  lang: "Français"
  lang_short: "fr"
  color: "#a038ec"
  image: ""
  favicon: "src/img/favicon.png"
  sitemap: "src/xml/sitemap.xml"

# Labs/test IP authorization Configuration
labs:
  enable: false
  labsIPAuth:
    - 127.0.0.1

# Other
other:
  website_version: 4.1.0-alpha
  
  use_database: false
  db_in_env:
    # add database login in .env (recommended to true)
    auto_add_db_in_env: true

  # .env informations
  env:
    # if true all value in .env will be automatically added in $_ENV
    use_env: true
    auto_generate_env: true
    
    admin:
      add_login_admin: true
      # admin password automattically hashed (changed automatically in .env if you change it)
      admin_password: "kerogs"

framework:
  framework_version: 2.4.3-sh16
  title: "KerogsPHP Framework"
  title_short: "KsPHP Framework"